name: deploy-container
 
on:
  push:
    branches:
      - master
    paths:
      - "4_linking_multiple_apps/dashboard_react_vue/container/**"
 
defaults:
  run:
    working-directory: 4_linking_multiple_apps/dashboard_react_vue/container
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build